### ISSUE TITLE
OrbitControls addEventListener not a function

### ISSUE THREAD

**Issue by mikegoodstadt** [Itee/three-full#10]
Hi - thanks for generating this library!
I am getting an error when trying to use the OrbitControls:
TypeError: window.addEventListener is not a function at new OrbitControls
which refers to line 238 of OrbitControls.js:
window.removeEventListener( 'keydown', onKeyDown, false );

I have created a StackBlitz and would appreciate any help resolving this:
https://stackblitz.com/edit/angular-three-full

P.S. I have a working version of the same code but using three-orbitcontrols-ts but would like to minimize my dependencies and so prefer three-full...:
https://stackblitz.com/edit/angular-three-orbitcontrols

**Comment by Itee** [comment]
I'm currently unable to update the version hosted by stackblitz to v11.3.1. I will give it a try later.

Please re-open if needed.

**Comment by Itee** [comment]
After some test i found that this fix break the cjs build. A new one is now release under v11.3.2
