### ISSUE TITLE
Update to Three.js r99

### ISSUE THREAD

**Issue by marcatec** [Itee/three-full#18]
This pull request [Converted .glsl files to .glsl.js #15280](https://github.com/mrdoob/three.js/pull/15280) in three.js brought a big change.
The current converter can handle .glsl files but not .glsl.js.
How could that be fixed.
Most former changes in three.js just needed some simple addition to the edge cases.

**Comment by 93Alliance** [comment]
I think so too

**Comment by Itee** [comment]
See #21 
Thanks.
