### ISSUE TITLE
Question: Possible to load CTMLoader in es6

### ISSUE THREAD

**Issue by michaellashinsky** [Itee/three-full#2]
More of a question and could be tagged as such, but is there any clean way to use the CTMLoader as an es6 import.  That is to say I have a base64 encoded string, change that into a ctm file, and load it using the CTMLoader all in es6 authored code?  I see that you have ctm folder listed under workers and I am not sure what that means.

**Comment by Itee** [comment]
I know i'm a bit late but...

Currently all the CTM stuff isn't supported. This is due to problematic import about the CTMWorker.

I will give it a new try, with the new version of es-convertor.
