### ISSUE TITLE
Update Three-Full to latest version of ThreeJs

### ISSUE THREAD

**Issue by Itee** [Itee/three-full#21]
First of all, sorry to being late !

Lot of work, lot of children, lot of life...

I will upgrade this package for each missing version of ThreeJs. So 97, 98, 99, 100, 101.
You will be able to find the version you want.

But i will support only the latest for fix of course.
I hope the job will be done for this week-end.

Thanks for your patience and understanding.

**Comment by robhawkes** [comment]
Thanks @Itee! And no problem! I've been patiently waiting to upgrade the the latest version of Three.js as I much prefer to use your version than having to deal with the hassle of the standard Three.js examples / controllers / etc.

If you could document your process for migrating to the latest versions (eg. what to look out for, what to change) then I can try to help with future builds.

**Comment by robhawkes** [comment]
Not sure if you'll have a chance this time but r102 was released very recently so it'd be great to be completely caught up with the latest releases.

https://github.com/mrdoob/three.js/releases/tag/r102

**Comment by Itee** [comment]
@robhawkes Thanks for the help purpose. And yes i saw it.

I'm currently on r101 that introduce typescript but the current pipeline is broken due to a for-of loop in BufferGeometryUtils that i need to transform using a patch task under gulp or bigger replacement.

I'm currently thinking about a proper way to extend/refactor the transform pipeline. And i will (if i could) write more doc about the process. 

In fact the ThreeJs upgrade is quite simple to me. I just need to do some fast task (check patchs, update es6.conf) to make it available in the next release.

The current big lack in this package is a full test in html page for each files created under test folder. In an automated way i will be able to be sure that EACH part of three-full are usable.

**Comment by Itee** [comment]
This is done !

Enjoy.

**Comment by maximeq** [comment]
Hi !
First of all, thanks for the work, very useful :)

THREE revision 102 has a major bug with texture (automatic resize flip the texture). If by any chance you can find time to update to 104, would be great ! :)

Thank you !
