### ISSUE TITLE
11.3.3 No Core folder?

### ISSUE THREAD

**Issue by timothyallan** [Itee/three-full#22]
Heya, just updated to 11.3.3 and get this on compile now:
```
./node_modules/three-full/sources/renderers/webgl/WebGLGeometries.js
Module not found: Can't resolve '../../core/BufferAttribute.js' in '/Development/project/node_modules/three-full/sources/renderers/webgl'
```

Peeked in the sources folder, and it seems like `/core` isn't in there anymore! 11.3.2 worked great.

**Comment by webprofusion-chrisc** [comment]
Confirming this bug is present in 16.0.0 as well. The issue appears if you just use three-full to pull in examples like:
```ts
import { EquirectangularToCubeGenerator } from "three-full/sources/loaders/EquirectangularToCubeGenerator";
```

**Comment by Itee** [comment]
Mmmhh this is really weird ! All seems to work fine... I clearly saw the core folder in latest version.

@webprofusion-chrisc About `EquirectangularToCubeGenerator ` this class is not exported by EquirectangularToCubeGenerator  file only CubemapGenerator... I will fix it.

**Comment by Itee** [comment]
What bundler are you using ?

Using rollup i clearly see that BufferAttribute is include in WebGLGeometries.test.

Have you any kind of template to reproduce this issue ?

**Comment by webprofusion-chrisc** [comment]
@Itee this is within an Ionic 4 app which is Angular 7 and TypeScript 3.x using webpack.

**Comment by timothyallan** [comment]
That IS strange. I just installed 16 via `npm install --save three-full` and my node_modules/three-full folder is definitely missing `sources/core`. It's just a typescript project using create react app.

![screen shot 2019-03-03 at 9 09 58 am](https://user-images.githubusercontent.com/1995135/53698004-60343880-3d94-11e9-8a46-6ecbfaf6cf14.png)

**Comment by timothyallan** [comment]
and 11.3.2 using the same method...
![screen shot 2019-03-03 at 9 58 57 am](https://user-images.githubusercontent.com/1995135/53698521-02efb580-3d9b-11e9-8100-ed642442f2bf.png)

**Comment by Itee** [comment]
Wow this is so strange o_O !

The "core" folder is in [sources](https://github.com/Itee/three-full/tree/dev/sources). So except that `npm publish` filter the core folder i don't understand what happening here.

Currently the only work around that i see is to copy paste the core folder from github in your npm module... This is not maintainable but could help waiting a fix or better solution...

**Comment by Itee** [comment]
In [npm run kit](https://npm.runkit.com/three-full) (under v15.0.0) i can create BufferAttribute so the core module is in v15.0.0 at least.

**Comment by Itee** [comment]
OMFG !!! I found why... 

I upgrade my NPM to v6.8.0 and... [BAM](https://npm.community/t/npm-pack-leaving-out-files-6-8-0-only/5382)

Could you try the fix under v16.0.1 ?

**Comment by timothyallan** [comment]
Amazing find! I just installed again from scratch, which gets me 17, and there's our friend the core folder :)

**Comment by Itee** [comment]
Thanks for the feedback !

Ok so could i/you close ?

**Comment by timothyallan** [comment]
Thanks for making this library! ;) 
Done and closed!
