### ISSUE TITLE
ReferenceError: process is not defined

### ISSUE THREAD

**Issue by storkweb** [Itee/three-full#23]
Hi,
I tried your latest version (and as for the previous one) I always get that :
ReferenceError: process is not defined
from 'Three.cjs.js:8'
reverting to regular 'three' package, too bad, nice try thought :-)

**Comment by Itee** [comment]
Mmmh this come from the nodejs window protection... What is your target environment ? NodeJs or browser ?

**Comment by storkweb** [comment]
Browser

Thanks for taking the time

⁣Didier SZYLOWICZ / StorkWEB​

Le 4 mars 2019 à 23:56, à 23:56, Tristan VALCKE <notifications@github.com> a écrit:

**Comment by Itee** [comment]
After run 

`npm install three-full` 

in a file named test.js containing

```javascript
var three = require('three-full')
console.log(three.REVISION)
```

and running

`node test.js`

I got `102`

So this usage of cjs build under nodejs work.
But if you are targeting a browser environment, you should use the Three.es build !

Could you provide a little example where is located your import please. Thanks in advance.

**Comment by storkweb** [comment]
Hi Tristan,

IT WORKS !!! BUT... I don't understand it seems I did something wrong with my import statement, (re-)but I'm quite sure that I tried that (working) syntax before... The only difference I can think of is that I was developping under windows and since yesterday I switched to a Linux VM because the terminal (colors) is broken in the last Windows 10 update (again !), it shouldn't change anything...
Aaah last thought, I had a mismatch in babel's plugins versions... more likely :-)

Anyway, Sorry to have bothered you with my own problem, and THANK YOU for investigating
AGAIN GREAT JOB !

Best regards

Didier


[http://www.storkweb.fr/]Didier SZYLOWICZ

 (+33/0)6 31 80 79 53 [tel:+33631807953]
 didier.sz [callto:didier.sz]
 www.storkweb.fr [https://www.storkweb.fr/]
Le 05/03/2019 10:23:28, Tristan VALCKE <notifications@github.com> a écrit :
After run
npm install three-full
in a file named test.js containing
var three = require('three-full') console.log(three.REVISION)
and running
node test.js
I got 102
So this usage of cjs build under nodejs work.
But if you are targeting a browser environment, you should use the Three.es build !
Could you provide a little example where is located your import please. Thanks in advance.

**Comment by Itee** [comment]
You're welcome, and thanks to you for the feedback !

I never try yet to use this library under Linux.. This could be a future test to implement.

I'm enjoy to ear that your problem is solve. So i close this issue.
