### ISSUE TITLE
This repo and npm package are obsolete and need to be deleted

### ISSUE THREAD

**Issue by looeee** [Itee/three-full#29]
First of all, @Itee, thank you for making this package and all the hard work you put into maintaining it. It had an important influence on moving the conversion of three.js to es6 modules forward at a time when the conversation on the main repo had stalled.

However, that conversion is now complete - all part of three.js including the examples are available as es6 modules - and it's important that people use the up to date versions from the [official three.js package](https://www.npmjs.com/package/three).
rather than the versions from this repo which, as of now, are 5 releases out of date. 

Currently about 2000 people per week are downloading this module on npm. That's a lot of people getting outdated software! 

Could you please delete the npm package and archive this repo?

**Comment by Itee** [comment]
You're all welcome ! This was hard work yeah ^^

I'm proud to helped the Three repo to take a decision on modules !

I'm currently still using this repo for my own purpose, but i will add a notice of deprecation on it.
I need to upgrade this repository to the latest threejs version for my current work. But i will move on threejs modules asap i could.

Thanks for all.
