### ISSUE TITLE
HDRCubeTextureLoader throws error

### ISSUE THREAD

**Issue by stealth86** [Itee/three-full#5]
When i create a new THREE.HDRCubeTextureLoader() and use the load() method , it gives error saying about this.manager is undefined. in the actual three.js examples, the loader has scope.manager, but in the three-full, it has this.manager.

its in this function below

function loadHDRData( i, onLoad, onProgress, onError ) {

		var loader = new FileLoader( this.manager );

**Comment by stealth86** [comment]
Any upcoming plans to upgrade three-full to r95

**Comment by Itee** [comment]
This should be ok now. If not please reopen, thanks.
