### ISSUE TITLE
DRACOLoader.js missing imports

### ISSUE THREAD

**Issue by viperphase1** [Itee/three-full#9]
Hello,
In the DRACOLoader.js file several BufferAttribute types are being used but only Uint16BufferAttribute and Uint32BufferAttribute have been imported.

You just need to include the rest in this block:
import {
&nbsp;&nbsp;&nbsp;&nbsp;Uint16BufferAttribute,
&nbsp;&nbsp;&nbsp;&nbsp;Uint32BufferAttribute
} from '../core/BufferAttribute.js'

**Comment by Itee** [comment]
It seems you're using an old version of three-full.

Uint16BufferAttribute and Uint32BufferAttribute are already imported by DRACOLoader since v6.0.0.

Which version of three-full are you using ?
